title = "LemonSignal"                                             # From Git
gitRepoUrl = "https://github.com/data-oriented-house/LemonSignal" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = [
	"Signal",
	"Connection"
]

[home]
enabled = true
includeReadme = false

[[home.features]]
title = ""
description = ""

[[home.features]]
title = "Speed and Convenience"
description = "LemonSignal is a modification of GoodSignal optimized for speed and extended functionality for no extra cost."
image = "/Lemon.png"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.ico"

# From git:
organizationName = "Data-Oriented-House"
projectName = "LemonSignal"
url = "https://data-oriented-house.github.io"
baseUrl = "/LemonSignal/"
tagline = "The Luau Signal Faster Than Most"

[navbar]


[navbar.logo]
src = "favicon.ico"

[footer]
style = "dark"
copyright = "Copyright © 2023 Aspecky. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"
