[package]
name = "caveful-games/limesignal"
version = "0.1.6"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
authors = ["jiwonz"]
description = "A fork of LemonSignal with additional features added"
realm = "shared"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
	"src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]
threadpool = "caveful-games/threadpool@0.1.4"
